#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 05:00:00
#SBATCH -J bwa_02
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load bwa
module load samtools

cd ../analyses/

bwa index 01_genome_assembly/genome_assembly.contigs.fasta
wait
for f in 03_preprocessing/*1P.fastq.gz
do
	echo $f
	echo ${f/1P/2P}
	bwa mem 01_genome_assembly/genome_assembly.contigs.fasta \
	$f ${f/1P/2P} -t 2 | samtools sort -o 04_mapping/${f:17:10}_mapped.bam
done
