#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 15:00:00
#SBATCH -J Canu_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load canu

# Your commands
canu \
 -p genome_assembly \
 -d ../analyses/01_genome_assembly/ \
 genomeSize=3m \
 useGrid=False \
 corThreads=2 \
 -pacbio ../data/DNA_raw_data/ERR2028*
