#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 01:00:00
#SBATCH -J Fast_QC_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load FastQC

# Your commands
fastqc \
 -p genome_assembly \
 -o ../analyses/05_FastQC/ \
 corThreads=2 \
../data/RNA_raw_data/ERR*
