#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:30:00
#SBATCH -J blastn_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load blast

# Your commands
blastn -query ../analyses/01_genome_assembly/genome_assembly.contigs.fasta \
-subject ../data/reference/OBMB01.fasta \
-out ../analyses/01_genome_assembly/evaluation/nblast_result \
