#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 05:00:00
#SBATCH -J preprocessing_05
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load trimmomatic/0.36
module load FastQC

# Your commands
fastqc \
 -o ../analyses/03_preprocessing/pre_trimming \
../data/RNA_raw_data/ERR*

trimmomatic PE -threads 2 -phred33 ../data/RNA_raw_data/ERR2036629_1.fastq.gz ../data/RNA_raw_data/ERR2036629_2.fastq.gz \
-baseout ../analyses/03_preprocessing/ERR2036629_trimmed.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5

trimmomatic PE -threads 2 -phred33 ../data/RNA_raw_data/ERR2036630_1.fastq.gz ../data/RNA_raw_data/ERR2036630_2.fastq.gz \
-baseout ../analyses/03_preprocessing/ERR2036630_trimmed.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5

trimmomatic PE -threads 2 -phred33 ../data/RNA_raw_data/ERR2036631_1.fastq.gz ../data/RNA_raw_data/ERR2036631_2.fastq.gz \
-baseout ../analyses/03_preprocessing/ERR2036631_trimmed.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5

trimmomatic PE -threads 2 -phred33 ../data/RNA_raw_data/ERR2036632_1.fastq.gz ../data/RNA_raw_data/ERR2036632_2.fastq.gz \
-baseout ../analyses/03_preprocessing/ERR2036632_trimmed.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5

trimmomatic PE -threads 2 -phred33 ../data/RNA_raw_data/ERR2036633_1.fastq.gz ../data/RNA_raw_data/ERR2036633_2.fastq.gz \
-baseout ../analyses/03_preprocessing/ERR2036633_trimmed.fastq.gz \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5

fastqc \
 -o ../analyses/03_preprocessing/post_trimming \
../analyses/03_preprocessing/ERR*




