#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:10:00
#SBATCH -J prokka_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load prokka

# Your commands
prokka \
 --outdir ../analyses/02_annotation/result \
 --prefix annotation \
 ../analyses/01_genome_assembly/genome_assembly.contigs.fasta
