#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:30:00
#SBATCH -J quast_04
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load quast/4.5.4

# Your commands
quast.py ../analyses/01_genome_assembly/genome_assembly.contigs.fasta \
-R ../data/reference/OBMB01.fasta \
-o ../analyses/01_genome_assembly/evaluation \
-t 1
