#!/bin/bash -l

#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J trimmomatic_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user polder.magdalena@gmail.com


# Load modules
module load bioinfo-tools
module load trimmomatic

# Your commands

trimmomatic PE -threads 2 \
-trimlog ../analyses/06_trimmomatic/logfile \
../data/RNA_raw_data/ERR2036629_1.fastq.gz ../data/RNA_raw_data/ERR2036629_2.fastq.gz \
-baseout ../analyses/06_trimmomatic/trim1 \
ILLUMINACLIP:$TRIMMOMATIC_HOME/adapters/TruSeq3-PE.fa:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:1:3 MINLEN:50 MAXINFO:40:0.5
